apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transfer
  name: transfer
  namespace: eucastanpay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transfer
  template:
    metadata:
      labels:
        app: transfer
    spec:
      containers:
      - image: eucastan/transfer
        name: transfer
        resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: ledger-config
        - secretRef:
            name: ledger-secrets
        livenessProbe:
          httpGet:
            path: /live
            port: 8003
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
