// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Eucastan",
            "email": "support@eucastanpay.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts/{account_id}/balance": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get Account Balance from Ledger",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ledger"
                ],
                "summary": "Get Account Balance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ledger Account ID",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.AccountBalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{account_id}/reconcile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ledger"
                ],
                "summary": "Get Reconciliation Result",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ledger Account ID",
                        "name": "account_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ReconciliationResultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ledgers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ledger"
                ],
                "summary": "Get All Ledger Entries",
                "parameters": [
                    {
                        "enum": [
                            "credit",
                            "debit"
                        ],
                        "type": "string",
                        "description": "Entry Type",
                        "name": "entry_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.LedgerResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ledgers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ledger"
                ],
                "summary": "Get Ledger by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ledger ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.LedgerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.AccountBalanceResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "balance": {
                    "type": "integer"
                }
            }
        },
        "github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.LedgerResponse": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "amount": {
                    "type": "integer"
                },
                "balance_after": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "entry_type": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ReconciliationResult": {
            "type": "object",
            "properties": {
                "account_balance": {
                    "type": "integer"
                },
                "account_id": {
                    "type": "string"
                },
                "difference": {
                    "type": "integer"
                },
                "ledger_balance": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                },
                "reconciled_at": {
                    "type": "string"
                },
                "status": {
                    "description": "\"ok\" or \"discrepancy\"",
                    "type": "string"
                }
            }
        },
        "github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ReconciliationResultResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_Eucastan_eucastanpay_services_ledger_internal_dto_response.ReconciliationResult"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter: Bearer \u003cJWT\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ledger-zaji.onrender.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "EucastanPay Ledger Service API",
	Description:      "Authentication and Ledger Entry Service for EucastanPay.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
