basePath: /api/v1
definitions:
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_request.ReconciliationRequest:
    properties:
      to_account_no:
        type: integer
    required:
    - to_account_no
    type: object
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_request.TransferRequest:
    properties:
      amount:
        type: integer
      description:
        type: string
      mode:
        enum:
        - intraBank
        - interBank
        - own
        type: string
      to_account_no:
        type: integer
    required:
    - amount
    - mode
    - to_account_no
    type: object
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.MessageResponse:
    properties:
      message:
        type: string
    type: object
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.TransferResponse:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      description:
        type: string
      from_account_id:
        type: string
      from_account_no:
        type: integer
      from_balance_after:
        type: integer
      id:
        type: string
      idempotency_key:
        type: string
      is_reversed:
        type: boolean
      mode:
        type: string
      reference:
        type: string
      reversal_ref:
        type: string
      status:
        type: string
      step:
        type: string
      to_account_id:
        type: string
      to_account_no:
        type: integer
      to_balance_after:
        type: integer
      type:
        description: TRANSFER, REVERSE
        type: string
    type: object
  github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.UserTransferResponse:
    properties:
      data:
        $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.TransferResponse'
      message:
        type: string
    type: object
host: transfer-sby1.onrender.com
info:
  contact:
    email: support@eucastanpay.com
    name: Eucastan
  description: Authentication and Transfer Management Service for EucastanPay.
  license:
    name: MIT
  title: EucastanPay Transfer Service API
  version: "1.0"
paths:
  /account/{account_id}/reconcile:
    post:
      consumes:
      - application/json
      description: Reconciliation Account from Transfer service.
      parameters:
      - description: Reconciliation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_request.ReconciliationRequest'
      - description: Account Reconciliation
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Reconcile account
      tags:
      - Transfer
  /transfers:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.TransferResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List transfers
      tags:
      - Transfer
    post:
      consumes:
      - application/json
      description: Initiates transfer from one user to the other (sender and receiver).
      parameters:
      - description: Unique idempotency key
        in: header
        name: Idempotency-Key
        required: true
        type: string
      - description: Transfer Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_request.TransferRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.UserTransferResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: TransferFromUser Initiate transfer
      tags:
      - Transfer
  /transfers/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Transfer ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.TransferResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get transfer by ID
      tags:
      - Transfer
  /transfers/{reference}:
    post:
      consumes:
      - application/json
      description: Reverses transfer from receiver back to sender (receiver -> sender).
      parameters:
      - description: Unique idempotency key
        in: header
        name: Idempotency-Key
        required: true
        type: string
      - description: Transfer Reference
        in: path
        name: reference
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.UserTransferResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Eucastan_eucastanpay_services_transfer_internal_dto_response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Reverse transfer
      tags:
      - Transfer
schemes:
- https
securityDefinitions:
  BearerAuth:
    description: 'Enter: Bearer <JWT>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
