// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/transfer/transfer.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transfer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransferId       string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reference        string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Step             string                 `protobuf:"bytes,3,opt,name=step,proto3" json:"step,omitempty"`
	FromAccId        string                 `protobuf:"bytes,4,opt,name=from_acc_id,json=fromAccId,proto3" json:"from_acc_id,omitempty"`
	FromAccNo        int64                  `protobuf:"varint,5,opt,name=from_acc_no,json=fromAccNo,proto3" json:"from_acc_no,omitempty"`
	ToAccId          string                 `protobuf:"bytes,6,opt,name=to_acc_id,json=toAccId,proto3" json:"to_acc_id,omitempty"`
	ToAccNo          int64                  `protobuf:"varint,7,opt,name=to_acc_no,json=toAccNo,proto3" json:"to_acc_no,omitempty"`
	Amount           int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Description      string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Type             string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Status           string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Mode             string                 `protobuf:"bytes,13,opt,name=mode,proto3" json:"mode,omitempty"`
	ReversalRef      string                 `protobuf:"bytes,14,opt,name=reversal_ref,json=reversalRef,proto3" json:"reversal_ref,omitempty"`
	IsReversed       bool                   `protobuf:"varint,15,opt,name=is_reversed,json=isReversed,proto3" json:"is_reversed,omitempty"`
	FromBalanceAfter int64                  `protobuf:"varint,16,opt,name=from_balance_after,json=fromBalanceAfter,proto3" json:"from_balance_after,omitempty"`
	ToBalanceAfter   int64                  `protobuf:"varint,17,opt,name=to_balance_after,json=toBalanceAfter,proto3" json:"to_balance_after,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Transfer) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *Transfer) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transfer) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *Transfer) GetFromAccId() string {
	if x != nil {
		return x.FromAccId
	}
	return ""
}

func (x *Transfer) GetFromAccNo() int64 {
	if x != nil {
		return x.FromAccNo
	}
	return 0
}

func (x *Transfer) GetToAccId() string {
	if x != nil {
		return x.ToAccId
	}
	return ""
}

func (x *Transfer) GetToAccNo() int64 {
	if x != nil {
		return x.ToAccNo
	}
	return 0
}

func (x *Transfer) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transfer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transfer) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transfer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transfer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transfer) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Transfer) GetReversalRef() string {
	if x != nil {
		return x.ReversalRef
	}
	return ""
}

func (x *Transfer) GetIsReversed() bool {
	if x != nil {
		return x.IsReversed
	}
	return false
}

func (x *Transfer) GetFromBalanceAfter() int64 {
	if x != nil {
		return x.FromBalanceAfter
	}
	return 0
}

func (x *Transfer) GetToBalanceAfter() int64 {
	if x != nil {
		return x.ToBalanceAfter
	}
	return 0
}

func (x *Transfer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transfer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *ListTransfersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransfersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*Transfer            `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *ListTransfersResponse) GetTransfers() []*Transfer {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type ReverseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reference      string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AdminId        string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReverseRequest) Reset() {
	*x = ReverseRequest{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseRequest) ProtoMessage() {}

func (x *ReverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseRequest.ProtoReflect.Descriptor instead.
func (*ReverseRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *ReverseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReverseRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ReverseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReverseRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ReverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReverseResponse) Reset() {
	*x = ReverseResponse{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseResponse) ProtoMessage() {}

func (x *ReverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseResponse.ProtoReflect.Descriptor instead.
func (*ReverseResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *ReverseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReconcileAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileAccountRequest) Reset() {
	*x = ReconcileAccountRequest{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileAccountRequest) ProtoMessage() {}

func (x *ReconcileAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileAccountRequest.ProtoReflect.Descriptor instead.
func (*ReconcileAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *ReconcileAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReconcileAccountRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

type ReconcileAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileAccountResponse) Reset() {
	*x = ReconcileAccountResponse{}
	mi := &file_proto_transfer_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileAccountResponse) ProtoMessage() {}

func (x *ReconcileAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transfer_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileAccountResponse.ProtoReflect.Descriptor instead.
func (*ReconcileAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_transfer_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *ReconcileAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReconcileAccountResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_transfer_transfer_proto protoreflect.FileDescriptor

const file_proto_transfer_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/transfer/transfer.proto\x12\btransfer\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x05\n" +
	"\bTransfer\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x12\n" +
	"\x04step\x18\x03 \x01(\tR\x04step\x12\x1e\n" +
	"\vfrom_acc_id\x18\x04 \x01(\tR\tfromAccId\x12\x1e\n" +
	"\vfrom_acc_no\x18\x05 \x01(\x03R\tfromAccNo\x12\x1a\n" +
	"\tto_acc_id\x18\x06 \x01(\tR\atoAccId\x12\x1a\n" +
	"\tto_acc_no\x18\a \x01(\x03R\atoAccNo\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\r \x01(\tR\x04mode\x12!\n" +
	"\freversal_ref\x18\x0e \x01(\tR\vreversalRef\x12\x1f\n" +
	"\vis_reversed\x18\x0f \x01(\bR\n" +
	"isReversed\x12,\n" +
	"\x12from_balance_after\x18\x10 \x01(\x03R\x10fromBalanceAfter\x12(\n" +
	"\x10to_balance_after\x18\x11 \x01(\x03R\x0etoBalanceAfter\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"@\n" +
	"\x14ListTransfersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"I\n" +
	"\x15ListTransfersResponse\x120\n" +
	"\ttransfers\x18\x01 \x03(\v2\x12.transfer.TransferR\ttransfers\"\x8b\x01\n" +
	"\x0eReverseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\")\n" +
	"\x0fReverseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"W\n" +
	"\x17ReconcileAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\x03R\taccountNo\"H\n" +
	"\x18ReconcileAccountResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid2\x88\x02\n" +
	"\x0fTransferService\x12F\n" +
	"\x0fReverseTransfer\x12\x18.transfer.ReverseRequest\x1a\x19.transfer.ReverseResponse\x12Y\n" +
	"\x10ReconcileAccount\x12!.transfer.ReconcileAccountRequest\x1a\".transfer.ReconcileAccountResponse\x12R\n" +
	"\x0fGetAllTransfers\x12\x1e.transfer.ListTransfersRequest\x1a\x1f.transfer.ListTransfersResponseB7Z5github.com/Eucastan/eucastanpay/common/proto/transferb\x06proto3"

var (
	file_proto_transfer_transfer_proto_rawDescOnce sync.Once
	file_proto_transfer_transfer_proto_rawDescData []byte
)

func file_proto_transfer_transfer_proto_rawDescGZIP() []byte {
	file_proto_transfer_transfer_proto_rawDescOnce.Do(func() {
		file_proto_transfer_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transfer_transfer_proto_rawDesc), len(file_proto_transfer_transfer_proto_rawDesc)))
	})
	return file_proto_transfer_transfer_proto_rawDescData
}

var file_proto_transfer_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_transfer_transfer_proto_goTypes = []any{
	(*Transfer)(nil),                 // 0: transfer.Transfer
	(*ListTransfersRequest)(nil),     // 1: transfer.ListTransfersRequest
	(*ListTransfersResponse)(nil),    // 2: transfer.ListTransfersResponse
	(*ReverseRequest)(nil),           // 3: transfer.ReverseRequest
	(*ReverseResponse)(nil),          // 4: transfer.ReverseResponse
	(*ReconcileAccountRequest)(nil),  // 5: transfer.ReconcileAccountRequest
	(*ReconcileAccountResponse)(nil), // 6: transfer.ReconcileAccountResponse
	(*timestamppb.Timestamp)(nil),    // 7: google.protobuf.Timestamp
}
var file_proto_transfer_transfer_proto_depIdxs = []int32{
	7, // 0: transfer.Transfer.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: transfer.Transfer.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: transfer.ListTransfersResponse.transfers:type_name -> transfer.Transfer
	3, // 3: transfer.TransferService.ReverseTransfer:input_type -> transfer.ReverseRequest
	5, // 4: transfer.TransferService.ReconcileAccount:input_type -> transfer.ReconcileAccountRequest
	1, // 5: transfer.TransferService.GetAllTransfers:input_type -> transfer.ListTransfersRequest
	4, // 6: transfer.TransferService.ReverseTransfer:output_type -> transfer.ReverseResponse
	6, // 7: transfer.TransferService.ReconcileAccount:output_type -> transfer.ReconcileAccountResponse
	2, // 8: transfer.TransferService.GetAllTransfers:output_type -> transfer.ListTransfersResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_transfer_transfer_proto_init() }
func file_proto_transfer_transfer_proto_init() {
	if File_proto_transfer_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transfer_transfer_proto_rawDesc), len(file_proto_transfer_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transfer_transfer_proto_goTypes,
		DependencyIndexes: file_proto_transfer_transfer_proto_depIdxs,
		MessageInfos:      file_proto_transfer_transfer_proto_msgTypes,
	}.Build()
	File_proto_transfer_transfer_proto = out.File
	file_proto_transfer_transfer_proto_goTypes = nil
	file_proto_transfer_transfer_proto_depIdxs = nil
}
