// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/account/account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,3,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	AccountType   string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_account_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

func (x *Account) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ConfirmAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountNo int64                  `protobuf:"varint,1,opt,name=from_account_no,json=fromAccountNo,proto3" json:"from_account_no,omitempty"`
	ToAccountNo   int64                  `protobuf:"varint,2,opt,name=to_account_no,json=toAccountNo,proto3" json:"to_account_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAccountRequest) Reset() {
	*x = ConfirmAccountRequest{}
	mi := &file_proto_account_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAccountRequest) ProtoMessage() {}

func (x *ConfirmAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAccountRequest.ProtoReflect.Descriptor instead.
func (*ConfirmAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *ConfirmAccountRequest) GetFromAccountNo() int64 {
	if x != nil {
		return x.FromAccountNo
	}
	return 0
}

func (x *ConfirmAccountRequest) GetToAccountNo() int64 {
	if x != nil {
		return x.ToAccountNo
	}
	return 0
}

type ConfirmAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId string                 `protobuf:"bytes,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   string                 `protobuf:"bytes,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	FromUserId    string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      string                 `protobuf:"bytes,4,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	FromEmail     string                 `protobuf:"bytes,5,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	ToEmail       string                 `protobuf:"bytes,6,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	FromBalance   int64                  `protobuf:"varint,7,opt,name=from_balance,json=fromBalance,proto3" json:"from_balance,omitempty"`
	ToBalance     int64                  `protobuf:"varint,8,opt,name=to_balance,json=toBalance,proto3" json:"to_balance,omitempty"`
	FromStatus    string                 `protobuf:"bytes,9,opt,name=from_status,json=fromStatus,proto3" json:"from_status,omitempty"`
	ToStatus      string                 `protobuf:"bytes,10,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmAccountResponse) Reset() {
	*x = ConfirmAccountResponse{}
	mi := &file_proto_account_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmAccountResponse) ProtoMessage() {}

func (x *ConfirmAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmAccountResponse.ProtoReflect.Descriptor instead.
func (*ConfirmAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmAccountResponse) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *ConfirmAccountResponse) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *ConfirmAccountResponse) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *ConfirmAccountResponse) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *ConfirmAccountResponse) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

func (x *ConfirmAccountResponse) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *ConfirmAccountResponse) GetFromBalance() int64 {
	if x != nil {
		return x.FromBalance
	}
	return 0
}

func (x *ConfirmAccountResponse) GetToBalance() int64 {
	if x != nil {
		return x.ToBalance
	}
	return 0
}

func (x *ConfirmAccountResponse) GetFromStatus() string {
	if x != nil {
		return x.FromStatus
	}
	return ""
}

func (x *ConfirmAccountResponse) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,3,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	AccountType   string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_proto_account_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccountsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListAccountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAccountsRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

func (x *ListAccountsRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *ListAccountsRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *ListAccountsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ListAccountsRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListAccountsRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_proto_account_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetCreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditRequest) Reset() {
	*x = GetCreditRequest{}
	mi := &file_proto_account_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditRequest) ProtoMessage() {}

func (x *GetCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditRequest.ProtoReflect.Descriptor instead.
func (*GetCreditRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetCreditRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCreditRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

func (x *GetCreditRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetDebitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebitRequest) Reset() {
	*x = GetDebitRequest{}
	mi := &file_proto_account_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebitRequest) ProtoMessage() {}

func (x *GetDebitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebitRequest.ProtoReflect.Descriptor instead.
func (*GetDebitRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetDebitRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDebitRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

func (x *GetDebitRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetCreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditResponse) Reset() {
	*x = GetCreditResponse{}
	mi := &file_proto_account_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditResponse) ProtoMessage() {}

func (x *GetCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditResponse.ProtoReflect.Descriptor instead.
func (*GetCreditResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetCreditResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDebitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDebitResponse) Reset() {
	*x = GetDebitResponse{}
	mi := &file_proto_account_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDebitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDebitResponse) ProtoMessage() {}

func (x *GetDebitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDebitResponse.ProtoReflect.Descriptor instead.
func (*GetDebitResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{8}
}

func (x *GetDebitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAccountRequest) Reset() {
	*x = GetUserAccountRequest{}
	mi := &file_proto_account_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAccountRequest) ProtoMessage() {}

func (x *GetUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAccountRequest.ProtoReflect.Descriptor instead.
func (*GetUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_account_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{10}
}

func (x *GetBalanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBalanceRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNo     int64                  `protobuf:"varint,3,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Balance       int64                  `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	AccountType   string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_account_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{11}
}

func (x *GetAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAccountResponse) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

func (x *GetAccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountResponse) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *GetAccountResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetAccountResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AccountNo     int64                  `protobuf:"varint,3,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_account_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{12}
}

func (x *ActionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ActionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionRequest) GetAccountNo() int64 {
	if x != nil {
		return x.AccountNo
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_account_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_proto_rawDescGZIP(), []int{13}
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_account_account_proto protoreflect.FileDescriptor

const file_proto_account_account_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/account/account.proto\x12\aaccount\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n" +
	"\aAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_no\x18\x03 \x01(\x03R\taccountNo\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"c\n" +
	"\x15ConfirmAccountRequest\x12&\n" +
	"\x0ffrom_account_no\x18\x01 \x01(\x03R\rfromAccountNo\x12\"\n" +
	"\rto_account_no\x18\x02 \x01(\x03R\vtoAccountNo\"\xde\x02\n" +
	"\x16ConfirmAccountResponse\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\tR\vtoAccountId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x04 \x01(\tR\btoUserId\x12\x1d\n" +
	"\n" +
	"from_email\x18\x05 \x01(\tR\tfromEmail\x12\x19\n" +
	"\bto_email\x18\x06 \x01(\tR\atoEmail\x12!\n" +
	"\ffrom_balance\x18\a \x01(\x03R\vfromBalance\x12\x1d\n" +
	"\n" +
	"to_balance\x18\b \x01(\x03R\ttoBalance\x12\x1f\n" +
	"\vfrom_status\x18\t \x01(\tR\n" +
	"fromStatus\x12\x1b\n" +
	"\tto_status\x18\n" +
	" \x01(\tR\btoStatus\"\xbb\x02\n" +
	"\x13ListAccountsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_no\x18\x03 \x01(\x03R\taccountNo\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"D\n" +
	"\x14ListAccountsResponse\x12,\n" +
	"\baccounts\x18\x01 \x03(\v2\x10.account.AccountR\baccounts\"Y\n" +
	"\x10GetCreditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\x03R\taccountNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"X\n" +
	"\x0fGetDebitRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\x03R\taccountNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"-\n" +
	"\x11GetCreditResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x10GetDebitResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15GetUserAccountRequest\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x11GetBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\x03R\taccountNo\"\xd2\x02\n" +
	"\x12GetAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_no\x18\x03 \x01(\x03R\taccountNo\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x03R\abalance\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"e\n" +
	"\rActionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"account_no\x18\x03 \x01(\x03R\taccountNo\"*\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8b\x04\n" +
	"\x0eAccountService\x12?\n" +
	"\x06Credit\x12\x19.account.GetCreditRequest\x1a\x1a.account.GetCreditResponse\x12<\n" +
	"\x05Debit\x12\x18.account.GetDebitRequest\x1a\x19.account.GetDebitResponse\x12M\n" +
	"\x0eGetUserAccount\x12\x1e.account.GetUserAccountRequest\x1a\x1b.account.GetAccountResponse\x12Q\n" +
	"\x0eResolveAccount\x12\x1e.account.ConfirmAccountRequest\x1a\x1f.account.ConfirmAccountResponse\x12E\n" +
	"\n" +
	"GetBalance\x12\x1a.account.GetBalanceRequest\x1a\x1b.account.GetAccountResponse\x12M\n" +
	"\x0eGetAllAccounts\x12\x1c.account.ListAccountsRequest\x1a\x1d.account.ListAccountsResponse\x12B\n" +
	"\x0fActionOnAccount\x12\x16.account.ActionRequest\x1a\x17.account.ActionResponseB6Z4github.com/Eucastan/eucastanpay/common/proto/accountb\x06proto3"

var (
	file_proto_account_account_proto_rawDescOnce sync.Once
	file_proto_account_account_proto_rawDescData []byte
)

func file_proto_account_account_proto_rawDescGZIP() []byte {
	file_proto_account_account_proto_rawDescOnce.Do(func() {
		file_proto_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_account_proto_rawDesc), len(file_proto_account_account_proto_rawDesc)))
	})
	return file_proto_account_account_proto_rawDescData
}

var file_proto_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_account_account_proto_goTypes = []any{
	(*Account)(nil),                // 0: account.Account
	(*ConfirmAccountRequest)(nil),  // 1: account.ConfirmAccountRequest
	(*ConfirmAccountResponse)(nil), // 2: account.ConfirmAccountResponse
	(*ListAccountsRequest)(nil),    // 3: account.ListAccountsRequest
	(*ListAccountsResponse)(nil),   // 4: account.ListAccountsResponse
	(*GetCreditRequest)(nil),       // 5: account.GetCreditRequest
	(*GetDebitRequest)(nil),        // 6: account.GetDebitRequest
	(*GetCreditResponse)(nil),      // 7: account.GetCreditResponse
	(*GetDebitResponse)(nil),       // 8: account.GetDebitResponse
	(*GetUserAccountRequest)(nil),  // 9: account.GetUserAccountRequest
	(*GetBalanceRequest)(nil),      // 10: account.GetBalanceRequest
	(*GetAccountResponse)(nil),     // 11: account.GetAccountResponse
	(*ActionRequest)(nil),          // 12: account.ActionRequest
	(*ActionResponse)(nil),         // 13: account.ActionResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_proto_account_account_proto_depIdxs = []int32{
	14, // 0: account.Account.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: account.Account.updated_at:type_name -> google.protobuf.Timestamp
	14, // 2: account.ListAccountsRequest.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: account.ListAccountsRequest.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: account.ListAccountsResponse.accounts:type_name -> account.Account
	14, // 5: account.GetAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 6: account.GetAccountResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 7: account.AccountService.Credit:input_type -> account.GetCreditRequest
	6,  // 8: account.AccountService.Debit:input_type -> account.GetDebitRequest
	9,  // 9: account.AccountService.GetUserAccount:input_type -> account.GetUserAccountRequest
	1,  // 10: account.AccountService.ResolveAccount:input_type -> account.ConfirmAccountRequest
	10, // 11: account.AccountService.GetBalance:input_type -> account.GetBalanceRequest
	3,  // 12: account.AccountService.GetAllAccounts:input_type -> account.ListAccountsRequest
	12, // 13: account.AccountService.ActionOnAccount:input_type -> account.ActionRequest
	7,  // 14: account.AccountService.Credit:output_type -> account.GetCreditResponse
	8,  // 15: account.AccountService.Debit:output_type -> account.GetDebitResponse
	11, // 16: account.AccountService.GetUserAccount:output_type -> account.GetAccountResponse
	2,  // 17: account.AccountService.ResolveAccount:output_type -> account.ConfirmAccountResponse
	11, // 18: account.AccountService.GetBalance:output_type -> account.GetAccountResponse
	4,  // 19: account.AccountService.GetAllAccounts:output_type -> account.ListAccountsResponse
	13, // 20: account.AccountService.ActionOnAccount:output_type -> account.ActionResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_account_account_proto_init() }
func file_proto_account_account_proto_init() {
	if File_proto_account_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_account_proto_rawDesc), len(file_proto_account_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_account_account_proto_goTypes,
		DependencyIndexes: file_proto_account_account_proto_depIdxs,
		MessageInfos:      file_proto_account_account_proto_msgTypes,
	}.Build()
	File_proto_account_account_proto = out.File
	file_proto_account_account_proto_goTypes = nil
	file_proto_account_account_proto_depIdxs = nil
}
