// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/ledger/ledger.proto

package ledger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_ReconcileAccount_FullMethodName      = "/ledger.LedgerService/ReconcileAccount"
	LedgerService_GetAllLedgers_FullMethodName         = "/ledger.LedgerService/GetAllLedgers"
	LedgerService_GetLedgersByEntryType_FullMethodName = "/ledger.LedgerService/GetLedgersByEntryType"
	LedgerService_GetLedger_FullMethodName             = "/ledger.LedgerService/GetLedger"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	ReconcileAccount(ctx context.Context, in *ReconcileAccountRequest, opts ...grpc.CallOption) (*ReconcileResponse, error)
	GetAllLedgers(ctx context.Context, in *ListLedgersRequest, opts ...grpc.CallOption) (*ListLedgersResponse, error)
	GetLedgersByEntryType(ctx context.Context, in *ListLedgersEntryTypeRequest, opts ...grpc.CallOption) (*ListLedgersEntryTypeResponse, error)
	GetLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) ReconcileAccount(ctx context.Context, in *ReconcileAccountRequest, opts ...grpc.CallOption) (*ReconcileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileResponse)
	err := c.cc.Invoke(ctx, LedgerService_ReconcileAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetAllLedgers(ctx context.Context, in *ListLedgersRequest, opts ...grpc.CallOption) (*ListLedgersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgersResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetAllLedgers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedgersByEntryType(ctx context.Context, in *ListLedgersEntryTypeRequest, opts ...grpc.CallOption) (*ListLedgersEntryTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLedgersEntryTypeResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedgersByEntryType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetLedger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LedgerResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	ReconcileAccount(context.Context, *ReconcileAccountRequest) (*ReconcileResponse, error)
	GetAllLedgers(context.Context, *ListLedgersRequest) (*ListLedgersResponse, error)
	GetLedgersByEntryType(context.Context, *ListLedgersEntryTypeRequest) (*ListLedgersEntryTypeResponse, error)
	GetLedger(context.Context, *LedgerRequest) (*LedgerResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) ReconcileAccount(context.Context, *ReconcileAccountRequest) (*ReconcileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileAccount not implemented")
}
func (UnimplementedLedgerServiceServer) GetAllLedgers(context.Context, *ListLedgersRequest) (*ListLedgersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllLedgers not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedgersByEntryType(context.Context, *ListLedgersEntryTypeRequest) (*ListLedgersEntryTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgersByEntryType not implemented")
}
func (UnimplementedLedgerServiceServer) GetLedger(context.Context, *LedgerRequest) (*LedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedger not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_ReconcileAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReconcileAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReconcileAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReconcileAccount(ctx, req.(*ReconcileAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetAllLedgers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetAllLedgers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetAllLedgers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetAllLedgers(ctx, req.(*ListLedgersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedgersByEntryType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLedgersEntryTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedgersByEntryType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedgersByEntryType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedgersByEntryType(ctx, req.(*ListLedgersEntryTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetLedger(ctx, req.(*LedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReconcileAccount",
			Handler:    _LedgerService_ReconcileAccount_Handler,
		},
		{
			MethodName: "GetAllLedgers",
			Handler:    _LedgerService_GetAllLedgers_Handler,
		},
		{
			MethodName: "GetLedgersByEntryType",
			Handler:    _LedgerService_GetLedgersByEntryType_Handler,
		},
		{
			MethodName: "GetLedger",
			Handler:    _LedgerService_GetLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ledger/ledger.proto",
}
