apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account
  name: account
  namespace: eucastanpay
spec:
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: eucastan/account
        ports:
        - containerPort: 8002
        resources:
          requests:
            cpu: "512m"
            memory: "500Mi"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: account-config
        - secretRef:
            name: account-secrets
        livenessProbe:
          httpGet:
            path: /live
            port: 8003
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
        
